version: '3'

services:
  dev:
    platform: linux/amd64
    build: .
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    cap_add:
      - SYS_PTRACE  # Needed for some profiling tools
    security_opt:
      - seccomp:unconfined  # Also needed for profiling